spring:
  datasource:
    url: jdbc:mysql://hufs-cheongwon-db.c9c4ywqgumtc.ap-northeast-2.rds.amazonaws.com:3306/finnect
    username: admin
    password: cheong34!
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 60000  # 60초
      maximum-pool-size: 5
      minimum-idle: 2
      idle-timeout: 300000
      max-lifetime: 1200000
      connection-test-query: SELECT 1

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #        show_sql: true
        format_sql: false

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.orm.jdbc.bind: trace

jwt:
  secret: u9jN23kLso2P7q1aN7K72mH5sQ8J2XN9o3K7VtL+F2I=sdfjksaldfjksddjflskfjsfldksdfj
  accessExpiration: 3600000 # 1시간
  refreshExpiration: 604800000 # 7일
  emailExpiration: 600000 #10분
